#!/bin/bash

APP_NAME="/etc/pyowrt/main.py"
PID_FILE="/var/run/pyowrt.pid"

start() {
    if [ -f $PID_FILE ]; then
        echo "pyowrt sudah berjalan dengan PID $(cat $PID_FILE)"
    else
        echo "Memulai pyowrt..."
        python $APP_NAME > /dev/null &
        echo $! > $PID_FILE
        echo "pyowrt telah dimulai dengan PID $!"
    fi
}

stop() {
    if [ -f $PID_FILE ]; then
        PID=$(cat $PID_FILE)
        echo "Menghentikan pyowrt dengan PID $PID..."
        kill $PID
        rm $PID_FILE
        echo "pyowrt telah dihentikan."
    else
        echo "pyowrt tidak sedang berjalan."
    fi
}

cek() {
    if [ -f $PID_FILE ]; then
        PID=$(cat $PID_FILE)
        echo "pyowrt sudah berjalan dengan PID $PID..."
    else
        echo "pyowrt tidak sedang berjalan."
    fi
}

autorun() {
    if pgrep -f /etc/pyowrt/main.py > /dev/null; then
        echo "pyowrt Sudah Berjalan."
        logger "pyowrt Sudah Berjalan."
    else
        rm $PID_FILE
        python $APP_NAME > /dev/null &
        echo $! > $PID_FILE
        echo "Memulai pyowrt Di background."
        logger "Memulai pyowrt Di background."
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    cek)
        cek
        ;;
    auto)
        autorun
        ;;
    *)
        echo "Usage: $0 {start|stop|cek}"
        exit 1
        ;;
esac

exit 0
